### ISSUE TITLE
Every file listed as written

### ISSUE THREAD

**Issue by zvr** [eellak/gsoc2022--build-recorder#100]
Running the first test in the `tests` directory, it reports that every system file is also written to:

> p0      a       b:process .
> p0      b:cmd   "gcc -c f1.c" .
> p0      b:start "2022-09-30T07:58:43Z" .
> f0      a       file .
> f0      b:name  "/etc/ld.so.cache" .
> f0      b:hash  "c8ce857e31ed7dc80099f66cab1bd7c1ea130f70" .
> p0      b:reads f0 .
> p0      **b:writes**        f0 .
> f1      a       file .
> f1      b:name  "/lib/x86_64-linux-gnu/libc.so.6" .
> f1      b:hash  "db27b09035aef1f4fe19dbc116eda8a654bd1c07" .
> p0      b:reads f1 .
> p0      **b:writes**        f1 .

This is obviously not correct.

**Comment by fvalasiad** [comment]
@zvr Interesting the solution is posted [here](https://stackoverflow.com/questions/61923703/how-to-make-sense-of-o-rdonly-0)

apparently `purpose & O_RDONLY` is bound to fail. Sending a patch for it.
