### ISSUE TITLE
When to record filenames (and file contents)

### ISSUE THREAD

**Issue by zvr** [eellak/gsoc2022--build-recorder#17]
There are two types of file access:
- reading an existing file;
- writing a file (in most cases also creating it).

Given a (sub-)process that starts at Tstart and ends at Tend, a file access is between the time it's opened Topen and the time it's closed Tclose.

On a linear time line, we have:
```
-----Tstart ---------- Topen ---------- Tclose ---------- Tend -----
 t0             t1              t2                t3             t4
```

Where (in which timestamps, t0 to t4) should the recording of the filenames and file contents happen?

**Comment by fvalasiad** [comment]
@zvr That would be t1 for filenames and t3 for file contents.

t1 for filenames because we are actually reading the filenames just prior to the **Topen** syscall entry. The reason being that we have no guarantee if the char pointer given as a parameter to the `open` syscall will keep pointing to the filename after `open`'s return.

t3 for file contents because we want all planned modifications to the files to be complete before we actually fetch the file contents. That would be after the `close` syscall.

**Comment by zvr** [comment]
Hmm...

> t1 for filenames

exactly _how_ do you get filenames before the call to `open()` ?

> t3 for file contents

you are correct that for files being written, we have to wait for the `close()` to get their contents.
On the other hand, temporary files may not be available after this point.

Maybe we should differentiate depending whether the file was opened for reading or for writing.

- if it's for reading, the file remains unmodified, so we can read its contents at any point >= t2
- if it's for writing, we have to wait for completion, so we can read its contents at any point >= t3

By that, it might actually make sense to do everything at t4, after the program execution ends.

**Comment by fvalasiad** [comment]
> exactly how do you get filenames before the call to open() ?
Upon `open(2)` syscall  i will first steal the relative path from the tracee process the way i already do and then proceed to open said files in the ways listed:

- Path starting with / means that it's an absolute path and we should open it as is.
- Path not starting with / means it's a relative path and we will instead be opening /proc/${pid}/cwd/${relative_path}

If instead the syscall is `openat(2)` we have 2 scenarios:

- First argument being a file descriptor, in which case we should have kept a table matching each file descriptor to its corresponding previously opened file.
- First argument being `AT_FDCWD` which means the call should be treated the same way `open(2)` is treated.

> By that, it might actually make sense to do everything at t4, after the program execution ends.

What if they open and close a file more than once?

> On the other hand, temporary files may not be available after this point.
To be honest when i say t3 i actually mean upon the syscall `close(2)` encounter for reasons stated above.

- We don't want the file to be "modified" more than once, fetching the contents at the point it's closed ensures this.
- Even if they do open it again, it will be treated as yet another file usage resulting in a different checksum, something which I'd prefer over just keeping the last modification.

**Comment by zvr** [comment]
**Filenames**

A, oh, so you do wait for the `open()` call... Remember t1 above is any time after the subprocess starts executing.

I actually think it would be much, much, easier to do it _after_ a _successful_ return of the `open()`.
Keep in mind that when, for example, an `#include "foo.h"` directive is processed, the following takes place:
```
open("./foo.h") = -1 // ENOENT, file not found
open("dir1/foo.h") = -1 // ENOENT, file not found
open("dir2/foo.h") = -1 // ENOENT, file not found
open("some/other/dir//foo.h") = -1 // ENOENT, file not found
open("/and/another/dir/foo.h") = -1 // ENOENT, file not found
open("/finally/dir/foo.h") = 3 // file found
```
We don't want to record all these failed attempts.

**File contents**

> What if they open and close a file more than once?

If it's opened for reading, we don't care.  The problem is only in the case where the process writes a file and then overwrites it again. I'm not sure this is a realistic case, but no compelling reason to not do it right after `close()`. We might lose some temporary files, but maybe they were not important anyway...

**Comment by zvr** [comment]
OK, I think we are in agreement.

- Filenames _after_ `open()` has run and returned, so t2 in the diagram above
- File contents _after_ `close()` has run and returned, so t3 in the diagram above

(t0..t5 are timestamps at some point between the T events)

**Comment by fvalasiad** [comment]
OK, closing issue.
