### ISSUE TITLE
Autoconf checks

### ISSUE THREAD

**Issue by zvr** [eellak/gsoc2022--build-recorder#25]
Autoconf should check that all required syscalls and parameters / arguments are available.

**Comment by fvalasiad** [comment]
whoops, wrong issue

**Comment by fvalasiad** [comment]
@zvr I struggle to understand this issue though, do you mean that **autoconf** should for example check to see if `ptrace(2)` is available? I've never used **autoconf** before so i still am not really aware of its capabilities. I can definitely look into it though if you elaborate on what you mean by syscalls and arguments.

**Comment by zvr** [comment]
Yes, autoconf is the mechanism to generate a `configure` script that should check whether everything needed is available and how it runs.

In our case, we should be checking all that we use: `ptrace`, `PTRACE_GET_SYSCALL_INFO`, etc.

**Comment by fvalasiad** [comment]
@zvr To my understanding it seems like a tool that performs static checks. Although from my last pull request namely the one that performs `AC_CHECK_LIB(crypto, SHA1_Init)` inside **configure.ac** it seems as if it also instructs the compiler to link with libcrypto.

Then again it also allows you to configure(as the name implies) the build.

If both **configure.ac** and **Makefile.am** affect the resulting **Makefile**, what are really the differences between the two? I guess i should study a bit.

**Comment by fvalasiad** [comment]
@zvr i found this very interesting [book](https://www.star.bnl.gov/~liuzx/autobook.html). Hope it will clear all confusion.

**Comment by zvr** [comment]
The original official version is https://www.sourceware.org/autobook/autobook/autobook.html.

You should read the 2nd edition, if possible.
