### ISSUE TITLE
Only regular files should be hashed

### ISSUE THREAD

**Issue by zvr** [eellak/gsoc2022--build-recorder#26]
It seems that [every closed fd is hashed](https://github.com/eellak/gsoc2022--build-recorder/blob/c0cff461c724dbe5be566bd1310ea827431452d2/src/tracer.c#L144).

This should happen only on regular files, not everything.

**Comment by fvalasiad** [comment]
@zvr Hmmm regular files as if i should skip directories? Or even perhaps stdin stdout stderr?

**Comment by fvalasiad** [comment]
@zvr Should we add a check to see if a file is unregular in both `open` and `close` handles?

**Comment by zvr** [comment]
I think it would complicate things if we were to keep information only on some kinds of `open`.

Let's do everything the same, for starters, except content hashing which should be only done for regular files (not directories, sockets, devices, etc.)

**Comment by fvalasiad** [comment]
@zvr I was about to solve this issue by using `stat(2)` to check for non-regular files when i noticed that you already perform the check inside the hash function. Have i misunderstood the task at hand? What is it that we should be checking?
