### ISSUE TITLE
ignore, or correctly handle openat(2)

### ISSUE THREAD

**Issue by zvr** [eellak/gsoc2022--build-recorder#27]
Currently `openat(2)` processing [ignores the first argument](https://github.com/eellak/gsoc2022--build-recorder/blob/c0cff461c724dbe5be566bd1310ea827431452d2/src/tracer.c#L164).

Until it is handled correctly, it should be disabled, rather than produce wrong data,

**Comment by fvalasiad** [comment]
@zvr 

I am thinking of doing something like this:

`openat(2)`'s first argument is a file descriptor, we will see which file it refers to using the `open_files` array.

In the meantime i am thinking about converting open's relative path to an absolute path by getting the path denoted by `/proc/PID/cwd` and appending the relative path to it.

I am confident about `openat(2)`'s solution but not so much for `open(2)`'s one, is there a better way to do this?
