### ISSUE TITLE
handle zero-length files

### ISSUE THREAD

**Issue by zvr** [eellak/gsoc2022--build-recorder#28]
Zero-length files currently produce a crash.

Upon closing, they are supposed to be hashed, but the hashing function tries to `mmap(2)` the file, which fails for empty files.

Solutions: either

1. do not `mmap` / `madvise` on zero-length; or
2. return pre-computed hash value for such files

**Comment by fvalasiad** [comment]
@zvr this needs to be dealt with, the program crashes before i can test my exec trace implementation.
