### ISSUE TITLE
Trace more file operations

### ISSUE THREAD

**Issue by zvr** [eellak/gsoc2022--build-recorder#38]
Tracing files opened is not enough.

Typical code structure is:
- open temporary file
- write in temporary file
- close temporary file
- if everything ok, move temporary file to final name

Similar can be seen in larger scale when a browser (or maven) downloads a file: it writes at `filename.part` and at successful completion renames `filename.part` to `filename`.

Till now we would record the temporary file name, but not the final one.

**Comment by fvalasiad** [comment]
@zvr How does one go about moving a file in linux? I remember the existence of hardlinks which are essentially pointers to a system resource(namely the file) and could be duplicated, as well as symbolic links that instead point to hardlinks.

I guess moving between the same drive would only require to duplicate the hardlink and then remove the former without deleting the resource it was pointing to? But on the same note moving between different drives would be pretty much the equivelant to copying and then removing the original.

There doesn't seem to be any syscall talking about this, and mv's source is unexpectedly big, can i have an initial tip for where to look at?

**Comment by zvr** [comment]
`rename(2)`

**Comment by fvalasiad** [comment]
@zvr What will be the RDF format for this?

**Comment by fvalasiad** [comment]
What about:

`p1 b:rename 'oldpath':'newpath'?

After all in your example given. After the compiler closes the temporary file we stop tracking it and it's no longer stored in the `finfo` array of that process.

**Comment by fvalasiad** [comment]
@zvr I need it to proceed with the `rename(2)` tracing.

**Comment by fvalasiad** [comment]
@zvr Might i ask, what is the purpose of the `b:` prefix and in this case the `_:` prefix?

**Comment by zvr** [comment]
The `b:` prefix is our namespace, defined in the header of the file (currently with fake `example.org` URI, until we get to the final one and publish it somewhere.

The `_:` prefix is the reserved "unnamed" namespace for creating nodes that do not have any meaningful name.
