### ISSUE TITLE
Automake should not touch CFLAGS

### ISSUE THREAD

**Issue by zvr** [eellak/gsoc2022--build-recorder#4]
CFLAGS is a user variable and should not be set by `automake`.

If the value is needed for the program compilation, it should be in `AM_CFLAFS`; if it is a user preference, it should be specified when running `configure`.

**Comment by fvalasiad** [comment]
I'd prefer that these options are enforced upon anyone contributing to this project so i will add it as `AM_CFLAGS`

**Comment by zvr** [comment]
Please don't; for example, I use another set of flags for checking (has some more and disregards some)

Of course, before accepting any contribution you can run any tests you want.

**Comment by fvalasiad** [comment]
Okay closed the merge request and deleted the branch

**Comment by zvr** [comment]
Closed via #6
