### ISSUE TITLE
Unique identifiers when saving

### ISSUE THREAD

**Issue by zvr** [eellak/gsoc2022--build-recorder#52]
Every process and every file should get a unique identifier in the generated records.

For processes, since their `pid` is unique, I have been using:
```C
sprintf(pbuf, "pid%ld", (long) pid);
```

But what about files?

**Comment by fvalasiad** [comment]
@zvr Well what about a global static counter and an additional field `id` in `FILE_INFO`? Pretty much what i would do in modern programming languages.

**Comment by zvr** [comment]
You're completely right -- and much simpler than my first idea of yet another table where we would look up strings.
As a matter of fact, let's also do it for processes.

Feel free to add it.

**Comment by zvr** [comment]
Now that I thought more about it, why have it a number?
Let's make it directly a `char * outname;` with the correct value (`sprintf "p%d" or "f%d"`)
