### ISSUE TITLE
`FILE_INFO` and `PROCESS_INFO` `outname` aren't initialized.

### ISSUE THREAD

**Issue by fvalasiad** [eellak/gsoc2022--build-recorder#79]
Because they are currently initialized inside `next_finfo(3)` and `next_pinfo(3)`. Problem is that these two are called only when the corresponding arrays are out of memory.

**Comment by fvalasiad** [comment]
Well after some investigation the code is invalid in the sense that "if in bound" the object isn't constructed.

`if(index < capacity)`
`    return arr[index];`
`reallocate();`
'construct();'
'return arr[index];`

so we normally need to change it to:

`if(index < capacity) {`
`    construct();`
`    return arr[index];`
`}`
`reallocate();`
'construct();'
'return arr[index];`

but i suggest we should instead restructure it like this:

`if(index == capacity)`
`    reallocate();`
`construct();`
`return arr[index]`

because it's better :).

**Comment by zvr** [comment]
The original code was fine, as we 're talking about array elements -- there is nothing to construct.

I must be missing something...

**Comment by fvalasiad** [comment]
@zvr 

say for example the "outname" member field of `FILE_INFO` is initialized inside `next_finfo`.

`next_finfo` was previously only called in case `finfo_at` was given an index that was "out of bounds"(that is, greater than the array total capacity). In the scenario that it was "in bounds" it was merely returning a pointer to the corresponding index without initializing `outname`.

Now remember that the array has a default size of 32. Which means `next_finfo` will be called only upon each re-allocation.

`next_finfo` isn't only meant to re-allocate the buffer, but this is how it was used so far. `next_finfo` has also the responsibility of initializing the object. Something which should happen for each and every `FILE_INFO` in the range `[0,numfinfo]`.

**Comment by fvalasiad** [comment]
@zvr But in case you tried to run you would see that `next_pinfo` fails to do its job too, that is because of what i mentioned above, there is a bug. If `next_?info` was given an index that was less than capacity, it would just return the pointer to it directly without initializing `outname`.

**Comment by zvr** [comment]
The `next_[pf]info` functions simply return a pointer to a new element. No need to "construct" or initialize anything.

The caller, as soon as they get a return (`next_pinfo()`, for example), will fill the different items in the struct (`pid`, etc.) -- they should also do the same with `outname`.

**Comment by fvalasiad** [comment]
@zvr Alright i will handle it.
